// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualWardrobe.Api.Data;

#nullable disable

namespace VirtualWardrobe.Api.Migrations
{
    [DbContext(typeof(WardrobeDbContext))]
    partial class WardrobeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarmentColor", b =>
                {
                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.HasKey("ColorId", "GarmentId");

                    b.HasIndex("GarmentId");

                    b.ToTable("GarmentColor");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            ColorId = 2,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            ColorId = 3,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            ColorId = 4,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            ColorId = 5,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000005")
                        },
                        new
                        {
                            ColorId = 6,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006")
                        },
                        new
                        {
                            ColorId = 7,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007")
                        },
                        new
                        {
                            ColorId = 2,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008")
                        },
                        new
                        {
                            ColorId = 8,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009")
                        },
                        new
                        {
                            ColorId = 2,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010")
                        },
                        new
                        {
                            ColorId = 9,
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010")
                        });
                });

            modelBuilder.Entity("GarmentOccasion", b =>
                {
                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("OccasionId")
                        .HasColumnType("integer");

                    b.HasKey("GarmentId", "OccasionId");

                    b.HasIndex("OccasionId");

                    b.ToTable("GarmentOccasion");

                    b.HasData(
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001"),
                            OccasionId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002"),
                            OccasionId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003"),
                            OccasionId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004"),
                            OccasionId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000005"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006"),
                            OccasionId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007"),
                            OccasionId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007"),
                            OccasionId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008"),
                            OccasionId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008"),
                            OccasionId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009"),
                            OccasionId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009"),
                            OccasionId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010"),
                            OccasionId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010"),
                            OccasionId = 4
                        });
                });

            modelBuilder.Entity("GarmentSeason", b =>
                {
                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("GarmentId", "SeasonId");

                    b.HasIndex("SeasonId");

                    b.ToTable("GarmentSeason");

                    b.HasData(
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001"),
                            SeasonId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002"),
                            SeasonId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003"),
                            SeasonId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003"),
                            SeasonId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004"),
                            SeasonId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000005"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000005"),
                            SeasonId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006"),
                            SeasonId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007"),
                            SeasonId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007"),
                            SeasonId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008"),
                            SeasonId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008"),
                            SeasonId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009"),
                            SeasonId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009"),
                            SeasonId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010"),
                            SeasonId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010"),
                            SeasonId = 2
                        });
                });

            modelBuilder.Entity("GarmentStyleTag", b =>
                {
                    b.Property<Guid>("GarmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("StyleTagId")
                        .HasColumnType("integer");

                    b.HasKey("GarmentId", "StyleTagId");

                    b.HasIndex("StyleTagId");

                    b.ToTable("GarmentStyleTag");

                    b.HasData(
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001"),
                            StyleTagId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000001"),
                            StyleTagId = 2
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002"),
                            StyleTagId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000002"),
                            StyleTagId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003"),
                            StyleTagId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000003"),
                            StyleTagId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004"),
                            StyleTagId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000004"),
                            StyleTagId = 6
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000005"),
                            StyleTagId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000005"),
                            StyleTagId = 5
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006"),
                            StyleTagId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000006"),
                            StyleTagId = 5
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007"),
                            StyleTagId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000007"),
                            StyleTagId = 5
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000008"),
                            StyleTagId = 5
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009"),
                            StyleTagId = 3
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000009"),
                            StyleTagId = 4
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010"),
                            StyleTagId = 1
                        },
                        new
                        {
                            GarmentId = new Guid("10000000-0000-4000-8000-000000000010"),
                            StyleTagId = 6
                        });
                });

            modelBuilder.Entity("VirtualWardrobe.Api.Domain.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lavender"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cream"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mauve"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sage"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Burgundy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pink"
                        });
                });

            modelBuilder.Entity("VirtualWardrobe.Api.Domain.Garment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Size")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Garments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000001"),
                            Brand = "Demo Atelier",
                            Category = "Top",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Lavender Cardigan",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Cardigan",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000002"),
                            Brand = "Demo Atelier",
                            Category = "Top",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Cream Lace Blouse",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Blouse",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000003"),
                            Brand = "Demo Atelier",
                            Category = "Bottom",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Brown Flare Trousers",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Trousers",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000004"),
                            Brand = "Demo Atelier",
                            Category = "Bottom",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Blue Midi Skirt",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Skirt",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000005"),
                            Brand = "Demo Atelier",
                            Category = "Top",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Mauve Button-Up",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Shirt",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000006"),
                            Brand = "Demo Atelier",
                            Category = "Dress",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sage Wrap Dress",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Wrap dress",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000007"),
                            Brand = "Demo Atelier",
                            Category = "Shoes",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Black Ankle Boots",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Boots",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000008"),
                            Brand = "Demo Atelier",
                            Category = "Shoes",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Cream Sneakers",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Sneakers",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000009"),
                            Brand = "Demo Atelier",
                            Category = "Outerwear",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Burgundy Coat",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Coat",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000000000010"),
                            Brand = "Demo Atelier",
                            Category = "Dress",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Floral Sundress",
                            Notes = "Fictional demo garment.",
                            Status = "Active",
                            Subtype = "Sundress",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("VirtualWardrobe.Api.Domain.Occasion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Occasion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evening"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Weekend"
                        });
                });

            modelBuilder.Entity("VirtualWardrobe.Api.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spring"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Summer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fall"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Winter"
                        });
                });

            modelBuilder.Entity("VirtualWardrobe.Api.Domain.StyleTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StyleTag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Romantic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cozy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vintage"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Minimal"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Playful"
                        });
                });

            modelBuilder.Entity("GarmentColor", b =>
                {
                    b.HasOne("VirtualWardrobe.Api.Domain.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWardrobe.Api.Domain.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarmentOccasion", b =>
                {
                    b.HasOne("VirtualWardrobe.Api.Domain.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWardrobe.Api.Domain.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarmentSeason", b =>
                {
                    b.HasOne("VirtualWardrobe.Api.Domain.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWardrobe.Api.Domain.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarmentStyleTag", b =>
                {
                    b.HasOne("VirtualWardrobe.Api.Domain.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWardrobe.Api.Domain.StyleTag", null)
                        .WithMany()
                        .HasForeignKey("StyleTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
